<?php

declare(strict_types=1);

namespace Fp\Collections;

use Fp\Functional\Option\Option;

/**
 * @template TK
 * @template-covariant TV
 * @psalm-immutable
 */
interface MapChainableOps
{
    /**
     * Produces new collection with given element
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->updated('b', 3)->toArray();
     * => [['a', 1], ['b', 3]]
     * ```
     *
     * @template TKI
     * @template TVI
     * @param TKI $key
     * @param TVI $value
     * @return Map<TK|TKI, TV|TVI>
     */
    public function updated(mixed $key, mixed $value): Map;

    /**
     * Produces new collection without an element with given key
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->removed('b')->toArray();
     * => [['a', 1]]
     * ```
     *
     * @param TK $key
     * @return Map<TK, TV>
     */
    public function removed(mixed $key): Map;

    /**
     * Filter collection by condition
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 1], ['b', 2]])->filter(fn(Entry $e) => $e->value > 1)->toArray();
     * => [['b', 2]]
     * ```
     *
     * @psalm-param callable(Entry<TK, TV>): bool $predicate
     * @psalm-return Map<TK, TV>
     */
    public function filter(callable $predicate): Map;

    /**
     * A combined {@see MapOps::map} and {@see MapOps::filter}.
     *
     * Filtering is handled via Option instead of Boolean.
     * So the output type TVO can be different from the input type TV.
     *
     * ```php
     * >>> HashMap::collectPairs([['a', 'zero'], ['b', '1'], ['c', '2']])
     * >>>     ->filterMap(fn(Entry $e) => is_numeric($e) ? Option::some((int) $e) : Option::none())
     * >>>     ->toArray();
     * => [['b', 1], ['c', 2]]
     * ```
     *
     * @psalm-template TVO
     * @psalm-param callable(Entry<TK, TV>): Option<TVO> $callback
     * @psalm-return Map<TK, TVO>
     */
    public function filterMap(callable $callback): Map;

    /**
     * Map collection and flatten the result
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['2', 2], ['5', 5]]);
     * => HashMap('2' -> 2, '5' -> 5)
     * >>> $collection
     * >>>     ->flatMap(fn(Entry $e) => [
     * >>>         [$e->value - 1, $e->value - 1],
     * >>>         [$e->value, $e->value],
     * >>>         [$e->value + 1, $e->value + 1]
     * >>>     ])
     * >>>     ->toArray();
     * => [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]]
     * ```
     *
     * @experimental
     * @psalm-template TKO
     * @psalm-template TVO
     * @psalm-param callable(Entry<TK, TV>): iterable<array{TKO, TVO}> $callback
     * @psalm-return Map<TKO, TVO>
     */
    public function flatMap(callable $callback): Map;

    /**
     * Alias for {@see MapOps::mapValues()}
     *
     * Produces a new collection of elements by mapping each element in collection
     * through a transformation function (callback)
     *
     * ```php
     * >>> $collection = HashMap::collect([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     * >>> $collection->map(fn(Entry $e) => $e->value + 1);
     * => HashMap('1' -> 2, '2' -> 3)
     * ```
     *
     * @template TVO
     * @psalm-param callable(Entry<TK, TV>): TVO $callback
     * @psalm-return Map<TK, TVO>
     */
    public function map(callable $callback): Map;

    /**
     * Produces a new collection of elements by mapping each element in collection
     * through a transformation function (callback)
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     * >>> $collection->mapValues(fn(Entry $e) => $e->value + 1);
     * => HashMap('1' -> 2, '2' -> 3)
     * ```
     *
     * @template TVO
     * @psalm-param callable(Entry<TK, TV>): TVO $callback
     * @psalm-return Map<TK, TVO>
     */
    public function mapValues(callable $callback): Map;

    /**
     * Produces a new collection of elements by assigning the values to keys generated by a transformation function (callback).
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     * >>> $collection->mapKeys(fn(Entry $e) => $e->value + 1);
     * => HashMap(2 -> 1, 3 -> 2)
     * ```
     *
     * @template TKO
     * @psalm-param callable(Entry<TK, TV>): TKO $callback
     * @psalm-return Map<TKO, TV>
     */
    public function mapKeys(callable $callback): Map;

    /**
     * Returns sequence of collection keys
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     * >>> $collection->keys(fn($elem) => $elem + 1)->toArray();
     * => ['1', '2']
     * ```
     *
     * @psalm-return Seq<TK>
     */
    public function keys(): Seq;

    /**
     * Returns sequence of collection values
     *
     * ```php
     * >>> $collection = HashMap::collectPairs([['1', 1], ['2', 2]]);
     * => HashMap('1' -> 1, '2' -> 2)
     * >>> $collection->values(fn($elem) => $elem + 1)->toArray();
     * => [1, 2]
     * ```
     *
     * @psalm-return Seq<TV>
     */
    public function values(): Seq;
}
